# Generated by Django 5.2.7 on 2026-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='city',
            field=models.CharField(default='', max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='country',
            field=models.CharField(default='', max_length=120, verbose_name='Страна'),
        ),
    ]
