FROM python:3.11-slim

WORKDIR /app

# Установим зависимости
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# Запускаем через daphne
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "core.asgi:application"]