# Generated by Django 5.2.7 on 2025-11-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('clients', '0001_initial'),
        ('performers', '0006_repertoireitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('interaction_type', models.CharField(choices=[('one_time', 'Разовое сотрудничество'), ('long_term', 'Долгосрочное сотрудничество')], max_length=32, verbose_name='Тип взаимодействия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('proposal_sent', 'Предложение отправлено'), ('in_discussion', 'Обсуждение'), ('agreement', 'Согласование'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', max_length=32, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Бюджет')),
                ('budget_currency', models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], default='RUB', max_length=3, verbose_name='Валюта бюджета')),
                ('success_flag', models.BooleanField(default=False, verbose_name='Успешно завершено')),
                ('result_notes', models.TextField(blank=True, verbose_name='Результаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='agents.agentprofile', verbose_name='Организатор')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='performers.performerprofile', verbose_name='Исполнитель')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='clients.clientprofile', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('note', 'Комментарий'), ('status_change', 'Изменение статуса'), ('file', 'Файл'), ('milestone', 'Этап')], default='note', max_length=32, verbose_name='Тип события')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='interactions/attachments/', verbose_name='Файл')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to=settings.AUTH_USER_MODEL, verbose_name='Автор события')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interactions.interaction', verbose_name='Взаимодействие')),
            ],
            options={
                'verbose_name': 'Событие взаимодействия',
                'verbose_name_plural': 'События взаимодействий',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Резюме проекта')),
                ('highlights', models.JSONField(blank=True, null=True, verbose_name='Ключевые моменты')),
                ('audience', models.CharField(blank=True, max_length=255, verbose_name='Аудитория / заказчик')),
                ('feedback', models.TextField(blank=True, verbose_name='Отзывы')),
                ('media_link', models.URLField(blank=True, verbose_name='Ссылка на материалы')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='interactions/reports/', verbose_name='Файл отчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор отчёта')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='interactions.interaction', verbose_name='Взаимодействие')),
            ],
            options={
                'verbose_name': 'Отчёт по проекту',
                'verbose_name_plural': 'Отчёты по проектам',
                'ordering': ['-created_at'],
            },
        ),
    ]
