# Generated by Django 5.2.7 on 2025-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('one_time', 'Разовое сотрудничество'), ('long_term', 'Долгосрочное сотрудничество')], max_length=32, verbose_name='Тип проекта'),
        ),
    ]
