# Generated by Django 5.2.7 on 2025-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('clients', '0001_initial'),
        ('interactions', '0002_alter_interaction_interaction_type'),
        ('performers', '0006_repertoireitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='venue',
        ),
        migrations.AddField(
            model_name='interaction',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='interactions', to='agents.agentprofile', verbose_name='Организаторы'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='interactions', to='performers.performerprofile', verbose_name='Исполнители'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='interactions', to='clients.clientprofile', verbose_name='Площадки'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
