# Generated by Django 5.2.7 on 2025-11-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_interactionparticipant_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='interactions.interaction', verbose_name='Проект'),
        ),
    ]
