# Generated by Django 5.2.7 on 2025-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_alter_projectreport_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='completion_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='completion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запрос завершения'),
        ),
        migrations.AddField(
            model_name='interactionparticipant',
            name='completion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запрос подтверждения'),
        ),
        migrations.AddField(
            model_name='interactionparticipant',
            name='completion_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ответ на подтверждение'),
        ),
        migrations.AddField(
            model_name='interactionparticipant',
            name='completion_status',
            field=models.CharField(choices=[('not_requested', 'Не запрошено'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('declined', 'Отклонено')], default='not_requested', max_length=20, verbose_name='Статус подтверждения завершения'),
        ),
    ]
