# Generated by Django 5.2.7 on 2026-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_add_interaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('one_time', 'Разовое сотрудничество'), ('long_term', 'Долгосрочное сотрудничество'), ('casting', 'Кастинг')], max_length=32, verbose_name='Тип проекта'),
        ),
    ]
