# Generated by Django 5.2.7 on 2026-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_venue_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Наименование площадки'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
