# Generated by Django 5.2.7 on 2026-07-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_legal_acceptance_cookie_consent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cookieconsent',
            new_name='accounts_co_user_id_56ed08_idx',
            old_name='accounts_co_user_id_7a0dde_idx',
        ),
        migrations.RenameIndex(
            model_name='legalacceptance',
            new_name='accounts_le_user_id_dc6383_idx',
            old_name='accounts_le_user_id_558330_idx',
        ),
    ]
