# Generated by Django 5.2.7 on 2026-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_co_user_id_7a0dde_idx_accounts_co_user_id_56ed08_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
    ]
