# Generated by Django 5.2.7 on 2025-10-13 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('voice_type', models.CharField(blank=True, max_length=100)),
                ('repertoire', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
