# Generated by Django 5.2.7 on 2025-10-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performerprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='performerprofile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performerprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performerprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='performers/photos/'),
        ),
    ]
