# Generated by Django 5.2.7 on 2025-10-21 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0002_remove_performerprofile_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performerprofile',
            name='calendar_mode',
            field=models.CharField(choices=[('mark_available', 'Отмечать доступные даты'), ('mark_unavailable', 'Отмечать занятые даты')], default='mark_unavailable', help_text='Режим заполнения календаря', max_length=20),
        ),
        migrations.CreateModel(
            name='PerformerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('unavailable', 'Занят'), ('maybe', 'Готов подумать')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='performers.performerprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('performer', 'date')},
            },
        ),
    ]
