# Generated by Django 5.2.7 on 2025-10-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0004_performerphoto_performervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='performerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Верифицирован ли профиль артиста'),
        ),
    ]
