# Generated by Django 5.2.7 on 2025-11-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0005_performerprofile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepertoireItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(help_text='Композитор (например: Моцарт В.А., Верди Дж.)', max_length=200)),
                ('work_title', models.CharField(help_text='Название произведения', max_length=300)),
                ('category', models.CharField(choices=[('opera', 'Опера'), ('operetta', 'Оперетта'), ('aria', 'Ария'), ('romance', 'Романс'), ('song', 'Песня'), ('chamber', 'Камерная музыка'), ('oratorio', 'Оратория'), ('cantata', 'Кантата'), ('mass', 'Месса/Реквием'), ('lieder', 'Lied'), ('other', 'Другое')], default='other', max_length=50)),
                ('epoch', models.CharField(blank=True, choices=[('renaissance', 'Ренессанс'), ('baroque', 'Барокко'), ('classical', 'Классицизм'), ('romantic', 'Романтизм'), ('modern', 'XX век'), ('contemporary', 'XXI век'), ('folk', 'Народная музыка')], max_length=50)),
                ('role_or_part', models.CharField(blank=True, help_text='Роль, партия или часть произведения', max_length=200)),
                ('year_performed', models.IntegerField(blank=True, help_text='Год исполнения (опционально)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки')),
                ('video_link', models.URLField(blank=True, help_text='Ссылка на YouTube или другой видеосервис')),
                ('is_featured', models.BooleanField(default=False, help_text='Выделить как избранное')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertoire_items', to='performers.performerprofile')),
            ],
            options={
                'ordering': ['-is_featured', 'order', 'composer', 'work_title'],
                'indexes': [models.Index(fields=['composer'], name='performers__compose_2a04a4_idx'), models.Index(fields=['work_title'], name='performers__work_ti_986d67_idx')],
            },
        ),
    ]
