# Generated by Django 5.2.7 on 2025-11-14 16:12

from django.db import migrations, models
from datetime import date


def convert_birth_year_to_birth_date(apps, schema_editor):
    """Конвертирует birth_year в birth_date (1 января указанного года)"""
    PerformerProfile = apps.get_model('performers', 'PerformerProfile')
    for profile in PerformerProfile.objects.exclude(birth_year__isnull=True):
        if profile.birth_year:
            profile.birth_date = date(profile.birth_year, 1, 1)
            profile.save(update_fields=['birth_date'])


def reverse_convert(apps, schema_editor):
    """Обратная конвертация: извлекает год из birth_date"""
    PerformerProfile = apps.get_model('performers', 'PerformerProfile')
    for profile in PerformerProfile.objects.exclude(birth_date__isnull=True):
        if profile.birth_date:
            profile.birth_year = profile.birth_date.year
            profile.save(update_fields=['birth_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0007_performerprofile_performer_type'),
    ]

    operations = [
        # Сначала добавляем новое поле
        migrations.AddField(
            model_name='performerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        # Конвертируем данные
        migrations.RunPython(convert_birth_year_to_birth_date, reverse_convert),
        # Удаляем старое поле
        migrations.RemoveField(
            model_name='performerprofile',
            name='birth_year',
        ),
    ]
