# Generated by Django 5.2.7 on 2026-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0009_performerprofile_photo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performerprofile',
            name='performer_type',
            field=models.CharField(choices=[('vocalist', 'Вокалист'), ('instrumentalist', 'Инструменталист'), ('conductor', 'Дирижер'), ('concertmaster', 'Концертмейстер')], default='vocalist', help_text='Основная специализация исполнителя', max_length=20),
        ),
    ]
