# Generated by Django 5.2.7 on 2026-08-13 11:07

from django.db import migrations, models


DEFAULT_INSTRUMENTS = [
    'Аккордеон', 'Альт', 'Арфа', 'Балалайка', 'Барабаны', 'Баян', 'Валторна',
    'Виолончель', 'Гитара', 'Гобой', 'Домра', 'Кларнет', 'Контрабас', 'Орган',
    'Саксофон', 'Скрипка', 'Тромбон', 'Труба', 'Туба', 'Ударные', 'Фагот',
    'Флейта', 'Фортепиано',
]


def seed_instruments(apps, schema_editor):
    MusicInstrument = apps.get_model('performers', 'MusicInstrument')
    MusicInstrument.objects.bulk_create(
        [MusicInstrument(name=name) for name in DEFAULT_INSTRUMENTS],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0010_alter_performerprofile_performer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Музыкальный инструмент',
                'verbose_name_plural': 'Музыкальные инструменты',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_instruments, migrations.RunPython.noop),
        migrations.AddField(
            model_name='performerprofile',
            name='city',
            field=models.CharField(default='', max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='performerprofile',
            name='country',
            field=models.CharField(default='', max_length=120, verbose_name='Страна'),
        ),
    ]
