# Generated by Django 5.2.7 on 2025-11-10 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(blank=True, help_text='Для быстрого фильтра по типу аккаунта', max_length=20, verbose_name='Роль автора')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('announcement_type', models.CharField(choices=[('need_performer', 'Ищем исполнителей'), ('need_venue', 'Ищем площадку'), ('collaboration', 'Совместный проект'), ('audition', 'Прослушивание'), ('contest', 'Конкурс'), ('other', 'Другое')], default='need_performer', max_length=32, verbose_name='Тип объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.JSONField(blank=True, null=True, verbose_name='Требования')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн откликов')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Бюджет')),
                ('budget_currency', models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Оплачиваемо')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архивировано')], default='draft', max_length=16, verbose_name='Статус')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено модератором')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
