# Generated by Django 5.2.7 on 2025-11-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_tag_alter_announcement_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_one_day',
            field=models.BooleanField(default=False, verbose_name='Одним днем'),
        ),
    ]
