# Generated by Django 5.2.7 on 2025-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_is_one_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архивировано'), ('completed', 'Завершено')], default='published', max_length=16, verbose_name='Статус'),
        ),
    ]
