# Generated by Django 5.2.7 on 2025-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
    ]
