# Generated by Django 5.2.7 on 2026-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_add_city_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='country',
            field=models.CharField(blank=True, max_length=120, verbose_name='Страна'),
        ),
    ]
