# Generated by Django 5.2.7 on 2026-09-07 11:52

import announcements.models
import announcements.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcement_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementResponseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=announcements.storage.PrivateAnnouncementStorage(), upload_to=announcements.models.response_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('content_type', models.CharField(max_length=100, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcementresponse', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Вложение отклика',
                'verbose_name_plural': 'Вложения откликов',
                'ordering': ('id',),
            },
        ),
    ]
