# Generated by Django 5.2.7 on 2025-11-14 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('chat_message', 'Новое сообщение в чате'), ('project_invitation', 'Приглашение в проект'), ('project_status_change', 'Изменение статуса проекта'), ('project_completion', 'Завершение проекта')], max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип связанного объекта')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'notification_type', 'is_sent'], name='notificatio_user_id_19c30c_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_f82ec2_idx')],
            },
        ),
    ]
