# Generated by Django 5.2.7 on 2026-02-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_read_state_and_preferences'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_user_id_1eba11_idx',
            old_name='notificatio_user_id_bf869e_idx',
        ),
    ]
