# Generated by Django 5.2.7 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_read_state_and_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('chat_message', 'Новое сообщение в чате'),
                    ('project_invitation', 'Приглашение в проект'),
                    ('project_status_change', 'Изменение статуса проекта'),
                    ('project_completion', 'Завершение проекта'),
                    ('announcement_tag_match', 'Новое объявление по вашим тегам'),
                ],
                max_length=50,
                verbose_name='Тип уведомления',
            ),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('chat_message', 'Новое сообщение в чате'),
                    ('project_invitation', 'Приглашение в проект'),
                    ('project_status_change', 'Изменение статуса проекта'),
                    ('project_completion', 'Завершение проекта'),
                    ('announcement_tag_match', 'Новое объявление по вашим тегам'),
                ],
                max_length=50,
                verbose_name='Тип уведомления',
            ),
        ),
    ]
