# Generated by Django 5.2.7 on 2026-02-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_announcement_notification_type'),
        ('notifications', '0003_rename_notificatio_user_id_bf869e_idx_notificatio_user_id_1eba11_idx'),
    ]

    operations = [
    ]
