# Generated by Django 5.2.7 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_merge_20260211_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email отправлен'),
        ),
        migrations.AddField(
            model_name='notification',
            name='in_app_sent',
            field=models.BooleanField(default=True, verbose_name='В приложении доступно'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('chat_message', 'Новое сообщение в чате'),
                    ('project_invitation', 'Приглашение в проект'),
                    ('project_status_change', 'Изменение статуса проекта'),
                    ('project_completion', 'Завершение проекта'),
                    ('announcement_tag_match', 'Новые подходящие объявления'),
                ],
                max_length=50,
                verbose_name='Тип уведомления',
            ),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('chat_message', 'Новое сообщение в чате'),
                    ('project_invitation', 'Приглашение в проект'),
                    ('project_status_change', 'Изменение статуса проекта'),
                    ('project_completion', 'Завершение проекта'),
                    ('announcement_tag_match', 'Новые подходящие объявления'),
                ],
                max_length=50,
                verbose_name='Тип уведомления',
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('notifications', 'Notification').objects.filter(email_sent=False, is_sent=True).update(email_sent=True),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
